/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Question {
  id: number
  questionId: number
  chapterId: number
  question: string
  answer: number
  optionA?: string
  optionB?: string
  optionC?: string
  optionD?: string
  explain?: string
  difficulty: number
  wrongRate: number
  optionType: number
}
export declare class QuestionDb {
  constructor(dbPath: string)
  close(): void
  getQuestions(): Array<Question>
  getQuestionById(id: number): Question | null
}
